name: Build
description: Build application with Maven and create a new Docker image
runs:
  using: composite
  steps:
  - name: Build with Maven
    run: |
      mvn -B package --file pom.xml
    shell: bash